### ISSUE TITLE
This solution no longer works after installing Azure CLI v2.30.0 or higher on the host

### ISSUE THREAD

**Issue by jdthorpe** [jongio/azureclicredentialcontainer#2]
To get this working, I had to downgrade to Azure CLI v2.29 or earlier on both the host and in the container.   In the Container this meant changing [this line](https://github.com/jongio/azureclicredentialcontainer/blob/5d183473e213e744fff03e53f8b7df0b50845637/src/net/Dockerfile#L16) to the following:

```dockerfile
RUN apt-get update \
    && apt-get install ca-certificates curl apt-transport-https lsb-release gnupg  -y

RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor | \
    tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

RUN AZ_REPO=$(lsb_release -cs) \
    && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
    tee /etc/apt/sources.list.d/azure-cli.list

RUN apt-get update && \
    apt-get install azure-cli=2.29.2-1~buster
```

and then installing the same version on the host machine from [the Azure CLI Releases page](https://github.com/Azure/azure-cli/releases)

**Comment by jongio** [comment]
Thanks. Yes, we are aware.  And are researching possible solutions. For now use the previous version in containers.

**Comment by goenning** [comment]
any ideas if we'll have a solution soon?

I've pinned our container to 2.29, but the az cli on devs machine are being auto upgraded by default, which shouldn't be happening by default.

**Comment by jongio** [comment]
Unfortunately, we don't have a solution.  Going to close this as it is being tracked here: https://github.com/Azure/azure-sdk-for-net/issues/19167
