### ISSUE TITLE
Need to install curl first before installing the AZ CLI 

### ISSUE THREAD

**Issue by saurabh-mridul** [jongio/azureclicredentialcontainer#4]
Awesome and easy solution, however I run in to issues while following the instructions. I realized that we also need to ensure that curl is installed on the container before we try installing the azure CLI, I have update the docker images as - 

FROM mcr.microsoft.com/dotnet/core/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["AzureCliCredentialContainer.csproj", "./"]
RUN dotnet restore "./AzureCliCredentialContainer.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "AzureCliCredentialContainer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AzureCliCredentialContainer.csproj" -c Release -o /app/publish

FROM base AS final
RUN apt-get clean && apt-get update 
RUN apt install curl -y
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AzureCliCredentialContainer.dll"]

**Comment by jongio** [comment]
Thanks.  Can you do a PR?

**Comment by saurabh-mridul** [comment]
here u go - https://github.com/jongio/azureclicredentialcontainer/pull/5
