### ISSUE TITLE
Azure CLI not installed

### ISSUE THREAD

**Issue by apetrut** [jongio/azureclicredentialcontainer#6]
Hi,

I am getting Azure CLI not installed error when running docker-compose even if I put the RUN commands in docker files.

The docker-compose loads 3 separate docker files which all contain this last step:

FROM base AS final
RUN apt-get clean && apt-get update
RUN apt install curl -y
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
ENTRYPOINT ["dotnet", "IdentityServer.dll"]

![image](https://user-images.githubusercontent.com/13006228/220671890-14710865-894a-4f1e-9ae7-65603bf5234f.png)

**Comment by jongio** [comment]
This solution no longer works, please see this issue https://github.com/Azure/azure-sdk-for-net/issues/19167
